do $$declare t text;begin foreach t in array array['profiles','user_scopes','commodities','commodity_rule_versions','crop_years','quality_marks','parties','banks','collateral_managers','godowns','godown_zones','inventory_transactions','lots','stock_ledger_entries','fifo_layers','fifo_consumptions','sales_orders','stock_controls','bank_pledges','pledge_lots','pledge_releases','weighments','fumigations','fumigation_lots','period_closings','import_batches','import_rows','alerts','audit_events','attachments'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy profiles_self_read on profiles for select to authenticated using(id=auth.uid());
create policy masters_read_commodities on commodities for select to authenticated using(true);
create policy masters_read_crop on crop_years for select to authenticated using(true);
create policy masters_read_quality on quality_marks for select to authenticated using(true);
create policy masters_read_parties on parties for select to authenticated using(true);
create policy masters_read_banks on banks for select to authenticated using(true);
create policy masters_read_cm on collateral_managers for select to authenticated using(true);
create policy masters_read_godowns on godowns for select to authenticated using(true);
create policy masters_read_zones on godown_zones for select to authenticated using(true);
create policy erp_read_transactions on inventory_transactions for select to authenticated using(true);
create policy erp_create_transaction on inventory_transactions for insert to authenticated with check(maker_user_id=auth.uid());
create policy erp_read_lots on lots for select to authenticated using(true);
create policy erp_read_ledger on stock_ledger_entries for select to authenticated using(true);
create policy erp_read_fifo on fifo_layers for select to authenticated using(true);
create policy erp_read_fifo_consumptions on fifo_consumptions for select to authenticated using(true);
create policy erp_read_orders on sales_orders for select to authenticated using(true);
create policy erp_read_controls on stock_controls for select to authenticated using(true);
create policy erp_read_pledges on bank_pledges for select to authenticated using(true);
create policy erp_read_pledge_lots on pledge_lots for select to authenticated using(true);
create policy erp_read_releases on pledge_releases for select to authenticated using(true);
create policy erp_read_fumigation on fumigations for select to authenticated using(true);
create policy erp_read_fumigation_lots on fumigation_lots for select to authenticated using(true);
create policy erp_read_periods on period_closings for select to authenticated using(true);
create policy erp_read_imports on import_batches for select to authenticated using(created_by=auth.uid() or exists(select 1 from profiles where id=auth.uid() and role_code='administrator'));
create policy erp_read_import_rows on import_rows for select to authenticated using(exists(select 1 from import_batches b where b.id=batch_id and (b.created_by=auth.uid() or exists(select 1 from profiles where id=auth.uid() and role_code='administrator'))));
create policy erp_read_alerts on alerts for select to authenticated using(true);
create policy erp_read_audit on audit_events for select to authenticated using(exists(select 1 from profiles where id=auth.uid() and role_code in('administrator','stock_accountant','auditor')));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('weighments','weighments',false,10485760,array['application/pdf','image/jpeg','image/png']),('inventory-documents','inventory-documents',false,20971520,array['application/pdf','image/jpeg','image/png','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/csv']),('pledge-documents','pledge-documents',false,20971520,array['application/pdf','image/jpeg','image/png']),('fumigation-documents','fumigation-documents',false,20971520,array['application/pdf','image/jpeg','image/png']),('imports','imports',false,52428800,array['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/csv']) on conflict(id) do nothing;
create policy storage_insert_erp on storage.objects for insert to authenticated with check(bucket_id in('weighments','inventory-documents','pledge-documents','fumigation-documents','imports'));
create policy storage_read_erp on storage.objects for select to authenticated using(bucket_id in('weighments','inventory-documents','pledge-documents','fumigation-documents','imports'));
