create or replace function public.upsert_godown(p_payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid;
begin
 if not public.is_admin() then raise exception 'Administrator permission required'; end if;
 v_id:=coalesce(nullif(p_payload->>'id','')::uuid,gen_random_uuid());
 insert into godowns(id,code,full_name,short_name,address_line_1,address_line_2,village_taluk,district,state,state_code,pincode,gstin,ownership,third_party_owner,warehouse_provider,agreement_reference,agreement_start,agreement_end,size_sq_ft,capacity_qty_kg,open_or_covered,responsible_employee,contact_number,is_active)
 values(v_id,upper(p_payload->>'code'),p_payload->>'full_name',p_payload->>'short_name',p_payload->>'address_line_1',p_payload->>'address_line_2',p_payload->>'village_taluk',p_payload->>'district',p_payload->>'state',upper(p_payload->>'state_code'),p_payload->>'pincode',p_payload->>'gstin',(p_payload->>'ownership')::godown_ownership,p_payload->>'third_party_owner',p_payload->>'warehouse_provider',p_payload->>'agreement_reference',nullif(p_payload->>'agreement_start','')::date,nullif(p_payload->>'agreement_end','')::date,nullif(p_payload->>'size_sq_ft','')::numeric,nullif(p_payload->>'capacity_qty_kg','')::numeric,p_payload->>'open_or_covered',p_payload->>'responsible_employee',p_payload->>'contact_number',coalesce((p_payload->>'is_active')::boolean,true))
 on conflict(id) do update set full_name=excluded.full_name,short_name=excluded.short_name,address_line_1=excluded.address_line_1,address_line_2=excluded.address_line_2,village_taluk=excluded.village_taluk,district=excluded.district,state=excluded.state,state_code=excluded.state_code,pincode=excluded.pincode,gstin=excluded.gstin,ownership=excluded.ownership,third_party_owner=excluded.third_party_owner,warehouse_provider=excluded.warehouse_provider,agreement_reference=excluded.agreement_reference,agreement_start=excluded.agreement_start,agreement_end=excluded.agreement_end,size_sq_ft=excluded.size_sq_ft,capacity_qty_kg=excluded.capacity_qty_kg,open_or_covered=excluded.open_or_covered,responsible_employee=excluded.responsible_employee,contact_number=excluded.contact_number,is_active=excluded.is_active,updated_at=now();
 insert into audit_events(user_id,action,entity_type,entity_id,details) values(auth.uid(),'upsert','godown',v_id,p_payload);
 return v_id;
end$$;
create or replace function public.reopen_period(p_period_id uuid,p_reason text) returns void language plpgsql security definer set search_path=public as $$begin if not public.is_admin() then raise exception 'Administrator permission required';end if;if length(trim(p_reason))<10 then raise exception 'A detailed reopening reason is required';end if;update period_closings set status='reopened',reopened_by=auth.uid(),reopened_at=now(),reopen_reason=p_reason where id=p_period_id and status='closed';if not found then raise exception 'Closed period not found';end if;insert into audit_events(user_id,action,entity_type,entity_id,details) values(auth.uid(),'reopen','period_closing',p_period_id,jsonb_build_object('reason',p_reason));end$$;
grant execute on function public.upsert_godown(jsonb),public.reopen_period(uuid,text) to authenticated;
